org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.parallel=true

loom.platform=forge

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.5
forge_version_range=[47,)
loader_version_range=[47,)
parchment_version=2023.09.03

mod_id=ritchiesfirearmengine
mod_name=Ritchies Firearm Engine
mod_license=MIT
mod_version=0.6.0
mod_group=rbasamoyai.ritchiesfirearmengine
mod_authors=rbasamoyai
mod_description=Flexible firearms pack mod.

# Dependencies

mixinextras_version=0.5.0

# QoL

moonlight_cf_file=6740431
dummy_mod_cf_file=6608233
configured_cf_file=5180900
